Repository your-news/service-repo, pull requests merged in 2022-10, with the labels that each got.

#58 feat: #39 필터검색 기능
  src/main/java/com/news/dto/SearchRequestDto.java
  src/main/java/com/news/dto/util/SearchUtil.java
  src/main/resources/static/basic.js
  src/main/resources/static/css/head.css
  src/main/resources/static/sidebar.js
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/sidebar.html
  src/main/resources/templates/result.html
Labels: enhancement

#64 fix: #44 jwt 수정, 로그인한 유저정보 가져오는 부분 수정
  src/main/java/com/news/config/JwtSecurityConfig.java
  src/main/java/com/news/config/SecurityConfig.java
  src/main/java/com/news/controller/UserController.java
  src/main/java/com/news/error/ErrorCode.java
  src/main/java/com/news/jwt/JwtFilter.java
  src/main/java/com/news/jwt/TokenProvider.java
  src/main/java/com/news/service/UserService.java
Labels: enhancement

#61 Feature/#60 opinions
  src/main/java/com/news/controller/PostController.java
  src/main/java/com/news/controller/ViewPageController.java
  src/main/java/com/news/dto/PostResponseDto.java
  src/main/java/com/news/entity/Post.java
  src/main/java/com/news/service/PostService.java
  src/main/resources/static/basic.js
  src/main/resources/static/css/post.css
  src/main/resources/static/signup.js
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/fragments/header.html
Labels: enhancement

#62 Hotfix
  src/main/resources/application.yaml
  src/main/resources/templates/fragments/header.html
Labels: bug, enhancement

#65 Feature/#63 ssl security
  src/main/java/com/news/config/ElasticsearchConfig.java
  src/main/resources/application-prod.yaml
Labels: enhancement

#68 메인에 머지된 코드가 동작하지 않아 코드를 수정함
  src/main/java/com/news/config/ElasticsearchConfig.java
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
Labels: bug

#73 fix: mariadb -> mysql로 변경함
  src/main/resources/application-prod.yaml
Labels: bug

#75 이메일/닉네임 중복체크 시, null 값이 보내지는 경우 에러가 터지는 로직 수정함
  src/main/java/com/news/controller/UserController.java
  src/main/resources/static/signup.js
Labels: bug

#71 feat: #59 페이지네이션 기능 추가
  src/main/java/com/news/dto/util/SearchUtil.java
  src/main/resources/static/basic.js
  src/main/resources/static/css/head.css
  src/main/resources/static/sidebar.js
  src/main/resources/templates/index.html
Labels: enhancement

#78 Feature/#72 검색기능 수정
  src/main/java/com/news/config/ElasticsearchConfig.java
  src/main/java/com/news/dto/util/SearchUtil.java
  src/main/java/com/news/helper/Indices.java
  src/main/java/com/news/service/NewsService.java
  src/main/resources/static/basic.js
  src/main/resources/templates/fragments/sidebar.html
Labels: enhancement
