Repository your-news/service-repo, pull requests merged in 2022-09, with the labels that each got.

#16 fix: #12 메인 view페이지 head 수정, css 파일명 변경
  src/main/resources/static/css/index.css
  src/main/resources/templates/index.html
Labels: enhancement

#18 fix: #17 ERD 변경으로 인한 Entity 수정
  src/main/java/com/news/model/Group.java
  src/main/java/com/news/model/Keyword.java
  src/main/java/com/news/model/Location.java
  src/main/java/com/news/model/News.java
  src/main/java/com/news/model/Organization.java
  src/main/java/com/news/model/Person.java
Labels: enhancement

#19 Feature/#12 resultpage
  src/main/resources/static/basic.js
  src/main/resources/static/css/head.css
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/resultpage.html
Labels: enhancement

#23 feat: #21 keyword 검색 기능 프론트, ajax 구현
  src/main/java/com/news/controller/ViewPageController.java
  src/main/java/com/news/dto/NewsDto.java
  src/main/resources/static/basic.js
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/fragments/header.html
Labels: enhancement

#25 Feature/#24 sidebar
  src/main/java/com/news/controller/ViewPageController.java
  src/main/resources/templates/fragments/sidebar.html
  src/main/resources/templates/result.html
  src/main/resources/templates/resultpage.html
Labels: enhancement

#34 Feature/#27 deploy
  .ebextensions/00-makeFiles.config
  .github/workflows/deploy.yml
  Procfile
  build.gradle
  src/main/java/com/news/controller/TestController.java
Labels: enhancement

#32 검색 시 버튼 클릭으로 검색
  src/main/resources/static/basic.js
  src/main/resources/static/css/head.css
Labels: enhancement

#37 feat: #36 환경변수 설정 파일 추가
  .gitignore
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application.yaml
Labels: documentation

#43 fix: rds를 mysql로 만들었는데 잘못 적어서 mysql로 변경함
  src/main/resources/application-prod.yaml
Labels: bug

#46 fix: application 파일에서 @SpringBootApplication 수정
  src/main/java/com/news/YourNewsApplication.java
Labels: bug

#47 Feature/#42 article
  src/main/java/com/news/YourNewsApplication.java
  src/main/java/com/news/controller/PostController.java
  src/main/java/com/news/entity/Post.java
  src/main/java/com/news/entity/Timestamped.java
  src/main/java/com/news/repository/PostRepository.java
  src/main/java/com/news/service/NewsService.java
  src/main/java/com/news/service/PostService.java
  src/main/resources/static/basic.js
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/index.html
Labels: enhancement

#48 Chore
  src/main/java/com/news/document/News.java
  src/main/resources/application-dev.yaml
  src/main/resources/static/basic.js
  src/main/resources/templates/fragments/footer.html
Labels: enhancement

#56 feat: #49 더보기 버튼 추가함
  src/main/resources/static/basic.js
Labels: enhancement
